// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: "src/config/.env" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node -r dotenv/config prisma/seed.ts dotenv_config_path=src/config/.env",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
